/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cursor`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/opp-detail`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/workspace`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Skeleton`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Markdown`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/ChatWidget`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/capture` | `/capture`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/docs` | `/docs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ideas` | `/ideas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/triage` | `/triage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/briefs/[id]` | `/briefs/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(tabs)'}/specs/[id]` | `/specs/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/cursor`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/opp-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/workspace`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/Skeleton`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/Markdown`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/ChatWidget`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/index`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/capture` | `/capture`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/docs` | `/docs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ideas` | `/ideas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/triage` | `/triage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/briefs/[id]` | `/briefs/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(tabs)'}/specs/[id]` | `/specs/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/cursor${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/opp-detail${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/workspace${`?${string}` | `#${string}` | ''}` | `/../components/ui/Skeleton${`?${string}` | `#${string}` | ''}` | `/../components/ui/Markdown${`?${string}` | `#${string}` | ''}` | `/../components/ui/ChatWidget${`?${string}` | `#${string}` | ''}` | `/../components/ui/index${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/capture${`?${string}` | `#${string}` | ''}` | `/capture${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/docs${`?${string}` | `#${string}` | ''}` | `/docs${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ideas${`?${string}` | `#${string}` | ''}` | `/ideas${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/triage${`?${string}` | `#${string}` | ''}` | `/triage${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cursor`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/opp-detail`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/workspace`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Skeleton`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Markdown`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/ChatWidget`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/capture` | `/capture`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/docs` | `/docs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ideas` | `/ideas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/triage` | `/triage`; params?: Router.UnknownInputParams; } | `${'/(tabs)'}/briefs/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/briefs/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/specs/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/specs/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(tabs)'}/briefs/[id]` | `/briefs/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(tabs)'}/specs/[id]` | `/specs/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
